<a href="https://colab.research.google.com/github/pranabsarma18/Machine-Learning-Technique/blob/main/Python%20Implementation/Naive_Bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt

# Bernoulli naive Bayes

Run the below cell to get the following variables:

`X` = Data matrix of shape $(n, d)$. All the features are binary taking values $0$ or $1$.

`y` = label vector. Labels are $0$ and $1$.

In [2]:
rng = np.random.default_rng(seed=1)
X1 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.7), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X2 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)
X3 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.6), rng.binomial(size = 50,n = 1, p =0.2))).reshape(-1, 1)
X4 = np.concatenate((rng.binomial(size = 50,n = 1, p =0.8), rng.binomial(size = 50,n = 1, p =0.1))).reshape(-1, 1)


X = np.column_stack((X1,X2,X3,X4))

y = np.concatenate((np.zeros(50, dtype= int), np.ones(50, dtype = int))).reshape(-1, 1)
permute = rng.permuted(range(100)) 

X = X[permute]
y = y[permute]


In [3]:
X.shape, y.shape

((100, 4), (100, 1))

## Question 1
If we train the naive Bayes model on the dataset, What will be the value of $\hat{p}$, the estimate for $P(Y=1)$? 



In [4]:
# Enter your solution here
y.mean()

0.5

## Question 2
What will be the value of $\hat{p}_0^0$, the estimate of $P(f_0=1|y=0)$?  Write your answer correct to two decimal places.



In [5]:
# Enter your solution here
p0_0 = ((X[:,0] == 1) & (y[:,0] == 0)).sum()/((y[:,0] == 0).sum())
p0_0

0.68

## Question 3
What will be the value of $\hat{p}_0^1$, the estimate of $P(f_0=1|y=1)$?  Write your answer correct to two decimal places.



In [6]:
# Enter your solution here
p1_0 = ((X[:,0] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())
p1_0

0.26

## Question 4
What will be the value of $\hat{p}_3^1$, the estimate of $P(f_3=1|y=1)$?  Write your answer correct to two decimal places.




In [7]:
# Enter your solution here
p1_3 = ((X[:,3] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())
p1_3

0.12

## Naive Bayes Parameters estimation:

In [8]:
p = y.mean()

p0_0 = ((X[:,0] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 0).sum())
p0_1 = ((X[:,1] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 0).sum())
p0_2 = ((X[:,2] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 0).sum())
p0_3 = ((X[:,3] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 0).sum())

p1_0 = ((X[:,0] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())
p1_1 = ((X[:,1] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())
p1_2 = ((X[:,2] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())
p1_3 = ((X[:,3] == 1) & (y[:,0] == 1)).sum()/((y[:,0] == 1).sum())

In [9]:
labels = np.unique(y)
for i in labels:
  X_c = X[y[:,0]==i]
  for j in range(X.shape[1]):
    print(f'P(f_{j}=1|y={i})=' , np.sum(X_c[:, j])/X_c.shape[0]) 

P(f_0=1|y=0)= 0.68
P(f_1=1|y=0)= 0.64
P(f_2=1|y=0)= 0.6
P(f_3=1|y=0)= 0.84
P(f_0=1|y=1)= 0.26
P(f_1=1|y=1)= 0.14
P(f_2=1|y=1)= 0.18
P(f_3=1|y=1)= 0.12


In [10]:
def estimates(X, y):
    p_hat = y.mean()
    labels = np.unique(y)
    est = np.zeros((len(labels), X.shape[1]))

    for i in range(len(labels)):
        X_c = X[y.flatten()==i]

        for j in range(X.shape[1]):
            est[i, j] = (X_c[:,j]).sum()/X_c.shape[0]
    
    return p_hat, est

In [11]:
p, est = estimates(X, y)

In [12]:
est

array([[0.68, 0.64, 0.6 , 0.84],
       [0.26, 0.14, 0.18, 0.12]])

In [13]:
p

0.5

In [14]:
def predict(x, p, est):
    p0 = 1 - p
    class0 = p0
    for i in range(len(x)):
        class0 = class0 * (est[0,i]**x[i]) * ((1 - est[0,i])**(1-x[i]))
    class1 = p
    for i in range(len(x)):
        class1 = class1 * (est[1,i]**x[i]) * ((1 - est[1,i])**(1-x[i]))
    
    if class0 > class1:
        print('Class 0')
    else:
        print('Class 1') 

## Question 5

What will be the predicted label for the point $[1, 0, 1, 0]$? 



In [15]:
# Enter your solution here
class_0 = p0_0*(1-p0_1)*p0_2*(1-p0_3)*(1-p) 
class_1 = p1_0*(1-p1_1)*p1_2*(1-p1_3)*p

if class_0 > class_1:
    print('Class 0')
else:
    print('Class 1')

Class 1


In [16]:
x = np.array([1,0,1,0])
predict(x, p, est)

Class 1


## Question 6

What will be the predicted label for the point $[1, 0, 1, 1]$? 



In [17]:
# Enter your solution here
x = np.array([1,0,1,1])
predict(x, p, est)

Class 0


# Gaussian naive Bayes

Run the below cell to get the following variables:

`X_train` = Training dataset of the shape $(n, d)$. All the examples are coming from multivariate gaussian distribution.

`y_train` = label vector for corresponding training examples. labels are $0$ and $1$.

`X_test` = Test dataset of the shape $(m, d)$, where $m$ is the number of examples in the test dataset. All the examples are coming from multivariate gaussian distribution.

`y_test` = label vector for corresponding test examples. labels are $0$ and $1$.



In [18]:
from sklearn.datasets import make_classification, make_blobs
from sklearn.model_selection import train_test_split

# generate artificial data points
X, y = make_blobs(n_samples = 100,
                  n_features=2, 
                  centers=[[5,5],[10,10]],
                  cluster_std=1.5,
                  random_state=2)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
                                                    random_state=123)

## Question 7

How many examples are there in the trianing dataset?



In [19]:
# Enter your solution here
X_train.shape[0]

80

## Question 8
How many features are there in the dataset?



In [20]:
# Enter your solution here
X_train.shape[1]

2

## Question 9

If we train the Gaussian naive Bayes model on the trianing dataset, What will be the value of $\hat{p}$, the estimate for $P(Y=1)$? Write your answer correct to two decimal places.





In [21]:
# Enter your solution here
y_train.mean()

0.4875

In [35]:
def Gestimates(X, y):
    p = y.mean()
    X0_train = X_train[y_train==0]
    X0_train_mean = X0_train.mean(axis=0)
    X0_train_var = X0_train.var(axis=0)

    X1_train = X_train[y_train==1]
    X1_train_mean = X1_train.mean(axis=0)
    X1_train_var = X1_train.var(axis=0)

    mu = np.vstack((X0_train_mean, X1_train_mean))
    var = np.vstack((X0_train_var, X1_train_var))

    return p, mu, var            

In [23]:
p, mu, var = Gestimates(X_train, y_train)

In [24]:
mu

array([[ 4.55853975,  5.01739665],
       [10.30431548, 10.08580617]])

In [25]:
var

array([[2.13298417, 2.30222002],
       [3.22242307, 2.20662074]])

## Question 10

If $\hat{\mu}_0 = [\mu_1, \mu_2, ..., \mu_d]$ be the estimate for $\mu_0$, the mean of $0$ labeled examples, what will be the value of $\mu_1+\mu_2+...+\mu_d$? Write your answer correct to two decimal places.



In [26]:
# Enter your solution here
X0_train = X_train[y_train==0]
X0_train_mean = X0_train.mean(axis=0)
X0_train_mean.sum()

9.575936394688135

In [27]:
mu[0].sum()

9.575936394688135

We will be using the different covariances for different labeled examples. The estimate for $\Sigma_k$ will be 

$$\hat{\Sigma}_k = \sigma_iI$$ where $\sigma_i$ is the variance of $i^{th}$ feature values of examples labeled $k$.



## Question 11
What will be value of $\text{trace}({\hat{\Sigma}}_0)$?  Write your answer correct to two decimal places.







In [28]:
# Enter your solution here
var[0].sum()

4.435204194501573

## Question 12

Once we have estimated all the parameters for Gaussian naive Bayes assuming the different covariance matrices, we predict the labels for the training examples. What will be the training accuracy?

Accuracy is defined as the proportion of correctly classified examples.  Write your answer correct to two decimal places.




In [33]:
# Enter your solution here
def G_pdf(x, mu, var, label):

    d = len(x)
    covar = np.diag(var[label])
    covar_inv = np.linalg.inv(covar)

    z = np.power(2 * np.pi, d/2) * np.power(np.linalg.det(covar), 1/2)
    return (1/z) * np.exp(-(x - mu[label]).T @ covar_inv @ (x - mu[label]))

In [42]:
def gnaive_pred(X, p, mu, var, labels):

    n = X.shape[0]
    d = X.shape[1]

    likelihood_prior = np.zeros((n, len(labels)))

    for i in range(n):
        for j in range(len(labels)):

            likelihood_prior[i, j] = np.log(G_pdf(X[i], mu, var, j)) + np.log((p**j) * ((1-p)**(1-j)))
    return np.argmax(likelihood_prior, axis=1)

In [43]:
labels = np.unique(y_train)
p, mu, var = Gestimates(X_train, y_train)
y_train_pred = gnaive_pred(X_train, p, mu, var, labels)

In [45]:
(y_train == y_train_pred).mean()*100

98.75

## Question 13

What will be the test accuracy?

Accuracy is defined as the proportion of correctly classified examples.  




In [47]:
# Enter your solution here
y_test_pred = gnaive_pred(X_test, p, mu, var, labels)

In [48]:
(y_test == y_test_pred).mean()*100

100.0